#pragma once

#include "Objects/object.c.h"
#include "Objects/tupleobject.c.h"
#include "Objects/frameobject.c.h"
#include "Objects/unicodeobject.c.h"

#include "Python/pylifecycle.c.h"
#include "Python/bltinmodule.c.h"
#include "Objects/moduleobject.c.h"

#include "Python/sysmodule.c.h"
#include "Objects/call.c.h"
#include "Objects/typeobject.c.h"
#include "Python/formatter_unicode.c.h"
#include "Objects/codeobject.c.h"
#include "Objects/floatobject.c.h"
#include "Objects/listobject.c.h"
#include "Objects/dictobject.c.h"
#include "Python/getargs.c.h"
#include "Objects/funcobject.c.h"
#include "Objects/descrobject.c.h"
#include "Objects/exceptions.c.h"
#include "Python/errors.c.h"
#include "Objects/classobject.c.h"
